# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Publish Nuget packages

on:
  push:
    branches:
    - release

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        
    - name: Creat Package dir
      run: mkdir packages
      
    - name: Build Core
      working-directory: "ECharts.Net"
      run: 'dotnet build --configuration Release && copy bin/Release/*.nupkg ../packages'
    - name: Build Webview2
      working-directory: "ECharts.Net.Webview2"
      run: 'dotnet build --configuration Release && copy bin/Release/*.nupkg ../packages'
    - name: Build WPF
      working-directory: "ECharts.Net.Wpf"
      run: 'dotnet build --configuration Release && copy bin/Release/*.nupkg ../packages'
    - name: Build Winform
      working-directory: "ECharts.Net.Winform"
      run: 'dotnet build --configuration Release && copy bin/Release/*.nupkg ../packages'
      
    - name: Publish 
      run: 'dotnet nuget push "packages/*.nupkg" -k ${{secrets.NUGET_KEY}} -s https://api.nuget.org/v3/index.json --skip-duplicate'
