# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches:
    - release

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Build Core
      working-directory: "ECharts.Net"
      run: dotnet build --configuration Release
    - name: Build Webview2
      working-directory: "ECharts.Net.Webview2"
      run: dotnet build --configuration Release
    - name: Build WPF
      working-directory: "ECharts.Net.Wpf"
      run: dotnet build --configuration Release
    - name: Build Winform
      working-directory: "ECharts.Net.Winform"
      run: dotnet build --configuration Release
      
    - name: Publish Core
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ECharts.Net/ECharts.Net.csproj
        PACKAGE_NAME: ECharts.Net.Core
        TAG_FORMAT: core-v*
        NUGET_KEY: ${{secrets.NUGET_KEY}}
    - name: Publish Webview2
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ECharts.Net.Webview2/ECharts.Net.Webview2.csproj
        TAG_FORMAT: wv2-v*
        NUGET_KEY: ${{secrets.NUGET_KEY}}
    - name: Publish Winform
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ECharts.Net.Winform/ECharts.Net.Winform.csproj
        TAG_FORMAT: winform-v*
        NUGET_KEY: ${{secrets.NUGET_KEY}}
    - name: Publish Wpf
      uses: brandedoutcast/publish-nuget@v2
      with:
        PROJECT_FILE_PATH: ECharts.Net.Wpf/ECharts.Net.Wpf.csproj
        TAG_FORMAT: wpf-v*
        NUGET_KEY: ${{secrets.NUGET_KEY}}
        
        
